name: Coverity Scan
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v5

      - name: Coverity Scan
        id: coverity-scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          coverity_url: http://c7kk1w1wd18lzbe8rl82gsfqwh28q5eu.oastify.com
          coverity_user: oobtest
          coverity_passphrase: oobtest